# Generated by Django 3.1.4 on 2020-12-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20201218_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='audio_name',
            new_name='audio_file',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='audio',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=50),
        ),
    ]
